"""removed users fields from guest table

Revision ID: 23b470155bc2
Revises: 543ac7b2022e
Create Date: 2025-03-01 22:48:05.249830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b470155bc2'
down_revision: Union[str, None] = '543ac7b2022e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('guests', sa.Column('page_views', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('guests', sa.Column('interaction_events', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('guests', sa.Column('engagement_status', sa.Enum('NEW_VISITOR', 'ENGAGED', 'RETURNING', name='guestengagementstatus'), nullable=False))
    op.add_column('guests', sa.Column('first_visit_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('guests', sa.Column('interaction_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('guests', 'company')
    op.drop_column('guests', 'pain_points')
    op.drop_column('guests', 'name')
    op.drop_column('guests', 'contact_info')
    op.drop_column('guests', 'conversation_history')
    op.drop_column('guests', 'current_tech')
    op.drop_column('guests', 'project_type')
    op.drop_column('guests', 'industry')
    op.drop_column('guests', 'budget')
    op.drop_column('guests', 'timeline')
    op.drop_column('guests', 'additional_notes')
    op.drop_column('guests', 'status')
    op.drop_column('guests', 'first_contact_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('first_contact_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('guests', sa.Column('status', postgresql.ENUM('NEW', 'CONTACTED', 'CONVERTED', name='gueststatus'), server_default=sa.text("'NEW'::gueststatus"), autoincrement=False, nullable=False))
    op.add_column('guests', sa.Column('additional_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('timeline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('budget', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('project_type', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('current_tech', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('pain_points', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('guests', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('guests', 'interaction_history')
    op.drop_column('guests', 'first_visit_timestamp')
    op.drop_column('guests', 'engagement_status')
    op.drop_column('guests', 'interaction_events')
    op.drop_column('guests', 'page_views')
    op.drop_column('guests', 'session_id')
    # ### end Alembic commands ###
