"""minio integration

Revision ID: 2a268f3644a1
Revises: 2f1be34c83ba
Create Date: 2025-03-09 12:25:04.228737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a268f3644a1'
down_revision: Union[str, None] = '2f1be34c83ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the table with foreign keys
    op.drop_table('resource_association')
    # Then drop the parent table
    op.drop_table('resources')
    
    # Create the new resources table with MinIO integration
    op.create_table('resources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),  # Keep it nullable for now
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_type', postgresql.ENUM('PDF', 'IMAGE', 'VIDEO', 'AUDIO', 'OTHER', name='resourcetype', create_type=True), nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(), nullable=True),
    sa.Column('source_url', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resources_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resources_pkey')
    )
    
    # Recreate the resource_association table
    op.create_table('resource_association',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('related_resource_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resources.id'], name='resource_association_related_resource_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='resource_association_resource_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'related_resource_id', name='resource_association_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resources_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resources_pkey')
    )
    op.create_table('resource_association',
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('related_resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resources.id'], name='resource_association_related_resource_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='resource_association_resource_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'related_resource_id', name='resource_association_pkey')
    )
    # ### end Alembic commands ###