"""modify resource table to be able to link resources

Revision ID: 32ea415e5c3c
Revises: ec2854e2098e
Create Date: 2025-03-07 22:59:28.338686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ea415e5c3c'
down_revision: Union[str, None] = 'ec2854e2098e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_association',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('related_resource_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'related_resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_association')
    # ### end Alembic commands ###
