"""combined guest old with new fields

Revision ID: 49036d12cd7a
Revises: aa243ffd35ae
Create Date: 2025-03-02 01:53:45.154472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49036d12cd7a'
down_revision: Union[str, None] = 'aa243ffd35ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('name', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('company', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('project_type', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('guests', sa.Column('budget', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('timeline', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('contact_info', sa.String(), nullable=True))
    op.add_column('guests', sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('guests', sa.Column('current_tech', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('guests', sa.Column('additional_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'additional_notes')
    op.drop_column('guests', 'current_tech')
    op.drop_column('guests', 'pain_points')
    op.drop_column('guests', 'contact_info')
    op.drop_column('guests', 'timeline')
    op.drop_column('guests', 'budget')
    op.drop_column('guests', 'project_type')
    op.drop_column('guests', 'industry')
    op.drop_column('guests', 'company')
    op.drop_column('guests', 'name')
    # ### end Alembic commands ###
