"""create guest table

Revision ID: 543ac7b2022e
Revises: 4adfa22e3b63
Create Date: 2025-02-28 20:53:24.337525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543ac7b2022e'
down_revision: Union[str, None] = '4adfa22e3b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('project_type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_tech', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('additional_notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', name='gueststatus'), nullable=False, server_default='NEW'),
    sa.Column('first_contact_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    
    # Drop enum type
    op.execute('DROP TYPE IF EXISTS gueststatus')
    # ### end Alembic commands ###
