"""make_nickname_nullable

Revision ID: 8a100fbfdb31
Revises: 49036d12cd7a
Create Date: 2025-03-03 18:45:52.302721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a100fbfdb31'
down_revision: Union[str, None] = '49036d12cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modified to only alter the nickname column to be nullable
    # The User model already has nullable=True for nickname, but this migration ensures the database matches
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # If we need to revert, make nickname non-nullable again
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
