"""changed status on guest table

Revision ID: aa243ffd35ae
Revises: 23b470155bc2
Create Date: 2025-03-02 00:08:46.681856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa243ffd35ae'
down_revision: Union[str, None] = '23b470155bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', name='gueststatus'), nullable=False))
    op.drop_column('guests', 'engagement_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('engagement_status', postgresql.ENUM('NEW_VISITOR', 'ENGAGED', 'RETURNING', name='guestengagementstatus'), autoincrement=False, nullable=False))
    op.drop_column('guests', 'status')
    # ### end Alembic commands ###
