"""modify resource model

Revision ID: ec2854e2098e
Revises: edfc3e4ed15e
Create Date: 2025-03-07 22:39:31.827477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2854e2098e'
down_revision: Union[str, None] = 'edfc3e4ed15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_association',
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('related_resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resources.id'], name='resource_association_related_resource_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='resource_association_resource_id_fkey'),
    sa.PrimaryKeyConstraint('resource_id', 'related_resource_id', name='resource_association_pkey')
    )
    # ### end Alembic commands ###
