"""added failed_login_attempts and is_locked to user table

Revision ID: effb157da083
Revises: 8a100fbfdb31
Create Date: 2025-03-06 06:44:06.934993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'effb157da083'
down_revision: Union[str, None] = '8a100fbfdb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the guests table already exists
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # Only create the guests table if it doesn't already exist
    if 'guests' not in tables:
        op.create_table('guests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('page_views', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('interaction_events', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('company', sa.String(), nullable=True),
        sa.Column('industry', sa.String(), nullable=True),
        sa.Column('project_type', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('budget', sa.String(), nullable=True),
        sa.Column('timeline', sa.String(), nullable=True),
        sa.Column('contact_info', sa.String(), nullable=True),
        sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('current_tech', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('additional_notes', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', name='gueststatus'), nullable=False),
        sa.Column('first_visit_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
        sa.Column('interaction_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Always add these columns since they are the main purpose of this migration
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'failed_login_attempts')
    
    # Only drop guests table if it exists
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'guests' in tables:
        op.drop_table('guests')
    # ### end Alembic commands ###
